name: "codesigner"
author: "E-Signer.com"
branding:
  icon: "feather"
  color: "green"
description: ""
inputs:
  command:
    description: "command to run"
    default: "--version"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
