name: "codesigner"
author: "E-Signer.com"
branding:
  icon: "feather"
  color: "green"
description: ""
inputs:
  command:
    description: ""
    required: true
    default: "--version"    
  username:
    description: ""
    required: false
  password:
    description: ""
    required: false
  credential-id:
    description: ""
    required: false
  totp-secret:
    description: ""
    required: false
  program-name:
    description: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
