on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
        with:
          command: |
            get_credential_ids -username '$ESIGNER_USERNAME' -password '$ES_PASSWORD'
