on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./
        env:
          ESIGNER_USERNAME: ${{ secrets.ESIGNER_USERNAME }}
          ESIGNER_PASSWORD: ${{ secrets.ESIGNER_PASSWORD }}
        with:
          command: |
            get_credential_ids -username "$ESIGNER_USERNAME" -password "$ESIGNER_PASSWORD"
