on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile Java Library
        shell: bash
        run: |
           javac src/HelloWorld.java -d ../build

      - name: Build Java Jar
        shell: bash
        run: |
          jar cmf src/HelloWorld.mf ../build/HelloWorld.jar ../build/HelloWorld.class src/HelloWorld.java

      - name: Run Action
        uses: ./
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: 8b072e22-7685-4771-b5c6-48e46614915f
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: build/HellowWorld.jar
          output_path: build/
