on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./
        with:
          command: get_credential_ids
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}} 
