on: [push]

jobs:
  codesigner:
    runs-on: ubuntu-latest
    name: Run CodeSigner Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile Java Library
        shell: bash
        run: |
          javac ${GITHUB_WORKSPACE}/src/HelloWorld.java -d ${GITHUB_WORKSPACE}/build

      - name: Build Java Jar
        shell: bash
        run: |
          jar cmf ${GITHUB_WORKSPACE}/src/HelloWorld.mf ${GITHUB_WORKSPACE}/build/HelloWorld.jar ${GITHUB_WORKSPACE}/build/HelloWorld.class ${GITHUB_WORKSPACE}/src/HelloWorld.java

      - name: Build Artifacts Directory
        shell: bash
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifacts

      - name: Sign Files
        uses: sslcom/actions-codesigner@master
        with:
          command: sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          file_path: ${GITHUB_WORKSPACE}/build/HelloWorld.jar
          output_path: ${GITHUB_WORKSPACE}/artifacts

      - name: Upload Signed Files
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorld.jar
          path: ./artifacts/HelloWorld.jar
